services:
  db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://db:27017  # لازم يطابق اللي في الكود عندك
    depends_on:
      - db

volumes:
  mongo-data: