services:
  app:
    
    image: nattie20/lab6-app:latest 
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://db:27017
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: mongo:latest
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - mongo_data:/data/db 
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongo_data: